version: "3.8"

services:
  postgres:
    image: postgres:16.4
    container_name: db_gestao_cursos
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: db_gestao_cursos
    ports:
      - "5435:5432"
    volumes:
      - db_gestao_cursos_data:/var/lib/postgresql/data

volumes:
  db_gestao_cursos_data:
    driver: local
